README.md
lib/fast_jsonapi/relationship.rb
spec/lib/object_serializer_relationship_links_spec.rb

Allow the definition of links on relationships to be declared as a method on the object.
For example:
```ruby
has_many :actors, links: :actor_relationship_links 
```

Allow relationship links to be declared as object method

---

lib/fast_jsonapi/object_serializer.rb
lib/fast_jsonapi/relationship.rb
lib/fast_jsonapi/serialization_core.rb
spec/lib/object_serializer_relationship_links_spec.rb
spec/lib/serialization_core_spec.rb

Resolves https://github.com/Netflix/fast_jsonapi/issues/357
When a relationship is listed under `include:`, it will add the data key to the record hash, allowing the included relationships to be reconstructed.

Include `data` key when lazy-loaded relationships are included

---

README.md
lib/fast_jsonapi/serialization_core.rb
spec/lib/object_serializer_class_methods_spec.rb

Hey thanks for creating this repo and keeping fast_jsonapi alive
---
A previous pull request added a block to the ObjectSerializer.set_id class
method, which allows passing a block to the set_id method. Currently
this block takes only one argument `record`:
```
set_id do |record|
"#{record.name.downcase}-#{record.id}"
end
```
This PR adds another argument params to the block:
```
set id do |record, params|
params[:admin] ?  record.id : "#{record.name.downcase}-#{record.id}"
end
```
This customization can be useful in situation where we serve different
clients that may need different IDs. One nice side effect is also that
the set_id method has the same method signature as the attribute
method.
This PR was copied from https://github.com/Netflix/fast_jsonapi/pull/380

Add params to set_id block

---

lib/fast_jsonapi/attribute.rb
lib/fast_jsonapi/link.rb
lib/fast_jsonapi/object_serializer.rb
lib/fast_jsonapi/scalar.rb
spec/lib/object_serializer_class_methods_spec.rb
spec/shared/contexts/movie_context.rb

See also Netflix/fast_jsonapi#442
Just like attribute, this PR allows the dev to specify links as follows:
```ruby
link(:download, if: ->(obj, params) { params && params[:signed_url] }) do |obj, params|
params[:signed_url]
end
```

Allow "if: Proc..." on link

---

lib/fast_jsonapi/object_serializer.rb
lib/fast_jsonapi/relationship.rb
spec/lib/object_serializer_inheritance_spec.rb
spec/lib/object_serializer_polymorphic_spec.rb

This is a duplicate of [my PR against the Netflix project](https://github.com/Netflix/fast_jsonapi/pull/446).
For polymorphic has_many relations, instead of getting the ids in a batch, the code loops over each object to get its type and id. In Relationship#id_hash_from_record it was hardcoded to get the id by calling record.id, which overrides the id_method_name options passed into the relationship.
I tried fixing this by only changing the code in Relationship to dynamically call the id_method_name on the object, but unfortunately on has_many relationships the default value for id_method_name would be passed as if the ids would be pulled in a batch (for example groupee_ids). That default works for regular has_manys where we get the ids all at once but fails for polymorphic ones where it …

Support for polymorphic `id_method_name`

---

README.md

This is just a minor change cleaning up some unnecessary whitespace in the code examples in the README. It also replaces the 3 backticks syntax with just single ones because those aren't needed for single-line code snippets.
I've first noticed these in the original Netflix repo but that looks unmaintained unfortunately. Good job on the fork by the way, hope this can be merged back eventually or Rubygems changed to point here.

Clean up some whitespace in the README

---

.github/workflows/ci.yml

CI doesn't run against ruby 2.7
CI runs against ruby 2.7
features)

Run CI against ruby 2.7

---

lib/fast_jsonapi/object_serializer.rb
lib/fast_jsonapi/relationship.rb
lib/fast_jsonapi/scalar.rb
lib/fast_jsonapi/serialization_core.rb
spec/lib/object_serializer_class_methods_spec.rb
spec/lib/object_serializer_spec.rb
spec/shared/contexts/movie_context.rb

Conditional procedures for scalars and relationships don't work when used with lambdas, for example:
```ruby
class MovieSerializer
include FastJsonapi::ObjectSerializer
attribute :release_year, if: ->(record) { record.release_year >= 2000 }
has_many :actors, if: ->(record) { record.actors.any? }
end
```
These currently throw an error: `ArgumentError: wrong number of arguments (given 2, expected 1)`.
This is very similar to the `&:proc` shorthand issue I've been working on at #58.
This change fixes the behavior to be able to use lambdas as well as `Proc`s with either one or two parameters.
This also includes the arity check for lambdas, which could be extracted to a common place.
features)

Fix conditional procedures with lambdas

---

README.md
lib/fast_jsonapi/object_serializer.rb
lib/fast_jsonapi/serialization_core.rb
spec/lib/object_serializer_caching_spec.rb
spec/shared/contexts/movie_context.rb

To enable caching, you must pass a cache store instance:
```rb
class UserSerializer
include FastJsonApi::ObjectSerializer
cache_store ActiveSupport::Cache::MemoryStore.new
end
```
To disable it, simply pass a falsy value:
```rb
class AdminUserSerializer < UserSerializer
cache_store false
end
```
Set race condition ttl and namespace:
```rb
class UserSerializer
include FastJsonApi::ObjectSerializer
cache_store ActiveSupport::Cache::MemoryStore.new(
race_condition_ttl: 20.seconds, namespace: 'my_caching_namespace'
)
end
```
- Very explicit where cache is stored
- No `Rails.cache` automagic with possible colliding keys
- Rails 5.2+ cache versioning support by using a cache that supports it
- Implicit namespace support (by cache instance, e.g.
`ActiveSupport::Cache::MemoryStore.new(namespace: …

refactor caching options and require own cache instance

---

lib/fast_jsonapi/object_serializer.rb
spec/lib/object_serializer_class_methods_spec.rb

I just noticed calling `attribute` with a lambda does not work: `attribute :key, ->(object) { ... }` and added a failing spec with a simple fix.
Since some work has been done recently to allow lambdas in addition to procs at various places I wonder if this should work here, too?

Fix #attribute with lambda

---

.github/workflows/ci.yml
CHANGELOG.md
lib/fast_jsonapi/version.rb

We need a release.
The releases (any tag on master) are automated and published to our GPR:
https://github.com/orgs/fast-jsonapi/packages?package_type=RubyGems
I also updated the changelog.
features)

Publish tagged releases on GPR.

---

CHANGELOG.md
lib/fast_jsonapi/object_serializer.rb
lib/fast_jsonapi/version.rb

ObjectSerializer#serialize_json does not accept arguments for to_json alias
ObjectSerializer#serialize_json accepts arguments for to_json alias.
Note the allowed arguments in the original to_json https://apidock.com/rails/Hash/to_json
features)

fix(ObjectSerializer): pass to_json arguments

---

CHANGELOG.md
lib/fast_jsonapi/relationship.rb

Specifying `:polymorphic` on a `belongs_to` relationship gives a static `record_type`.
Polymorphic relationships do not set a static `record_type`.  This allows a lookup of each record type.
features)

fix(Relationship): do not set static_record_type for polymorphic relationships

---

CHANGELOG.md
lib/fast_jsonapi/object_serializer.rb
lib/fast_jsonapi/version.rb

Removes the deprecated `ObjectSerializer#serialized_json`.  It's been a few months and the warnings are creating too much noise in our logs, it's time to say goodbye!

Remove ObjectSerializer#serialized_json

---

.github/workflows/ci.yml
README.md
jsonapi-serializer.gemspec
lib/fast_jsonapi/version.rb
lib/jsonapi/serializer.rb
lib/jsonapi/serializer/version.rb
spec/fixtures/_user.rb
spec/fixtures/actor.rb
spec/fixtures/movie.rb
spec/spec_helper.rb

We don't have a name to help with the releases #86 #1 
We have the `jsonapi-serializer` name which is an alias for the old `fast_jsonapi`.
features)

Rename the project

---

README.md

There is no example when using custom attributes with condition.
Added an example when using custom attributes with condition.
Closes #107 
features)

Add example for custom attribute with condition

---

lib/fast_jsonapi/object_serializer.rb
lib/fast_jsonapi/serialization_core.rb

Currently (v2.0.0), the logic for loading and serializing included records is highly-inefficient. Further, it appears to have an errant (albeit ignored) behavior. This inefficiency is exacerbated with a large and/or deeply nested set of included objects, which causes exponential growth in object allocation, iteration, and object checking.
Regarding the errant behavior, the current implementation attempts to query a parent object for all nested, included associations. Hard to describe, but using this library's spec fixtures as an example: If I serialize a Movie and ask to `include: [:actors, :'actors.played_movies']`, then the Movie instance is checked for both "actors" and "played_movies". Played movies should not be checked on the movie, only on the associated actors. The current library …

Performance optimize include behavior

---

CHANGELOG.md
README.md
lib/fast_jsonapi/serialization_core.rb
spec/integration/caching_spec.rb

This change alters the cache namespace prior to retrieving cached record
data to ensure that different fieldsets are given different cache keys.
Previously, all cache keys for the same record would be specified
identically, leading to a situation where the fieldset would be ignored
if record caching is enabled.
Fixes #90.
See #90 
The cache namespace is now altered prior to gathering cached entries with specific fieldsets. If a fieldset is specified, `"-fieldset:#{fieldset.join('_')"` will be appended to the cache namespace.
For example, if the fields `a`, `b`, and `c` were requested and the main namespace is `ns`, the generated namespace would be `ns-fieldset:a_b_c`.

Prevent incorrect fieldset caching

---

README.md
docs/json_serialization.md
lib/fast_jsonapi/instrumentation/skylight/normalizers/serializable_hash.rb
lib/fast_jsonapi/instrumentation/skylight/normalizers/serialized_json.rb
lib/generators/serializer/templates/serializer.rb.tt
spec/integration/attributes_fields_spec.rb
spec/integration/caching_spec.rb
spec/integration/errors_spec.rb
spec/integration/key_transform_spec.rb
spec/integration/links_spec.rb
spec/integration/meta_spec.rb
spec/integration/relationships_spec.rb

As the project has been renamed, its better to reflect it in the source code as well.
`JSONAPI::Serializer` is evaluated from `FastJsonapi::ObjectSerializer` so this change  probably will go unnoticed in gem usage.
Being a fast_jsonapi fork, FastJsonapi::ObjectSerializer is used.
As #86 has been resolved, the `fast_jsonapi` namespace should be replaced with the `jsonapi-serializer`.
As a first step the PR replaces FastJsonapi::ObjectSerializer with JSONAPI::Serializer.
TODO
features)

fix: Rename FastJsonapi::ObjectSerializer to JSONAPI::Serializer

---

lib/fast_jsonapi/object_serializer.rb

We assume a collection is to be serialized if the object has an `each` method. This causes inconsistencies, for ex #112 
We strictly try to detect if the object is an `Enumerable` as it's the commonly recommended way to detect collections.
Finally, this method is a public method now, and can be used by third-party libraries.
features)

Detect enumerables strictly. Closes #112

---

lib/fast_jsonapi/serialization_core.rb
spec/fixtures/_user.rb
spec/integration/caching_spec.rb

When using caching, the serialized hash differs from the one without caching because the empty `relationships` key is added. 
Changing the serialization logic so that the `relationships` key is added only if relationships are present.

Do not add empty relationships key

---

lib/fast_jsonapi.rb
lib/fast_jsonapi/object_serializer.rb
lib/jsonapi/serializer/errors.rb
spec/integration/errors_spec.rb

Currently the gem throws `ArgumentError` in case given include is not declared in serializer. `ArgumentError` is too broad and does not allow to safely rescue this error.
Particular use case:
I want to intercept this error and show it to end user as a validation error message. With the custom error class it is much easier to do. 
Serializers throw `JSONAPI::UnsupportedIncludeError` that is more specific and allows to retrieve invalid include value for validation response.

Raise FastJsonapi scoped error in case of unsupported include

---

README.md

(First time doing this, so please forgive me if I make a mistake)
Fix namespace to reflect new name
Per comment here - https://github.com/jsonapi-serializer/jsonapi-serializer/pull/139#discussion_r511688859
Change namespace from fastjson to jsonapi-serializer
```diff
- cache_options enabled: true, cache_length: 12.hours
+ cache_options store: Rails.cache, namespace: 'jsonapi-serializer', expires_in: 1.hour
- [NA] Tests for the changes have been added (for bug fixes / features)
- [Y] Docs have been reviewed and added / updated if needed (for bug fixes /
features)
- [NA] All automated checks pass (CI/CD)

Fix namespace name per comment in #139

---

README.md

this lambda yielding a bool for `belongs_to` might confuse readers or conflate the :if block
which would probably look something like this 
```ruby
belongs_to :primary_agent, if: proc { |movie, params| params[:current_user].present? } do |movie, params|
params[:current_user]
end
```
features)

Fix most likely copy/paste error

---

.github/workflows/ci.yml
lib/fast_jsonapi/helpers.rb
lib/fast_jsonapi/relationship.rb
lib/jsonapi/serializer/errors.rb
spec/fixtures/movie.rb

Fixes #158 (Shorthand Proc don't work with Ruby 3.0)
The Proc helper code uses the length of `Proc.parameters` to determine how many parameters the Proc/lambda accepts. However, lambdas created from a symbol (`&:foo`) take an unknown number of parameters, though they always take at least one, which is the 'receiver' object (i.e., an object that responds to the symbol).
In Ruby < 3.0 `Proc.parameters` for these lambdas always had a length of one with an unnamed parameter of type `rest`:
```
>> :foo.to_proc.parameters
=> [[:rest]]
```
This sort of worked since the proc helper just stuffed the record into the first parameter as the receiver. In Ruby 3.0, though, `Proc.parameters` now contains two unnamed elements:
```
>> :foo.to_proc.parameters
=> [[:req], [:rest]]
```
I assume that the …

Fix Ruby3 compatibility issue with Procs

---

.github/workflows/ci.yml
.rubocop.yml
jsonapi-serializer.gemspec
lib/fast_jsonapi/object_serializer.rb
lib/fast_jsonapi/serialization_core.rb
lib/jsonapi/serializer/instrumentation.rb
spec/fixtures/_user.rb
spec/fixtures/actor.rb
spec/spec_helper.rb

In addition to adding 3.1 to the list of Rubies in CI this PR:
1. Fixes the unquoted 3.0, which is currently truncated to '3'.  With that truncation, it loads the latest Ruby 3, which is 3.1.0.  Not the intention.
2. Fixes some layout and style lints
3. Adds the MFA required to gem publication, to satisfy Rubocop
4. Disables the gemspec required version cop.  If there's a desire to specify a minimum Ruby version the gemspec can be updated appropriately.
5. Explicitly requires 'active_support' before requiring any components.  This ensures that referenced ActiveSupport modules are properly loaded.  Discussion can be found [here](https://github.com/rails/rails/issues/43851)
CI is not green.  CI doesn't run against a 3.0.x Ruby.  Rubocop fails.
CI runs green.  CI runs against 2.4, 2.7, 3.0, …

Add Ruby 3.1 to CI

---

README.md

The current wording in the README has caused quite a lot of stir (see https://github.com/jsonapi-serializer/jsonapi-serializer/pull/141). It has also confused me in the past.
The README now better states the maintainer's intent as outlined in his response:
(source: https://github.com/jsonapi-serializer/jsonapi-serializer/pull/141#issuecomment-1028201018)

Clarify README wording related to contributions

---

README.md

There's no guide on how to order `has_many` relationship.
There will be a guide on how to order the `has_many` relationship in the `README.md` file.
features)

Add how to order `has_many` relationship

---

.github/workflows/ci.yml
jsonapi-serializer.gemspec
lib/extensions/has_one.rb
spec/integration/instrumentation_spec.rb
spec/spec_helper.rb

Ruby 3.2 is not in the CI matrix
The version of bundler installed is incompatible with Ruby on legacy Ruby jobs (2.4)
Rubocop fails
Truffleruby build fails because of simplecov errors
Ruby 3.2 is added to the Ci matrix
A compatible version of bundler is installed for Ruby 2.4
Rubocop finds no lints, allowing CI to pass
Simplecov is disabled for Truffleruby, allowing that job to pass
CI runs green.
Note this is intended as a PR for the current version of `jsonapi-serializer`, not the rewrite.
features)

Add Ruby 3.2 to the CI matrix
